# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thx < Formula
  desc "CLI for Things 3 on macOS"
  homepage "https://github.com/peeomid/thx"
  version "0.2.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/peeomid/thx/releases/download/v0.2.1/thx_Darwin_x86_64.tar.gz"
    sha256 "ce2e5b226c7b3d8926d02de627b5daefdf60cc3226926531275d5d383c9d5295"

    def install
      bin.install "thx"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/peeomid/thx/releases/download/v0.2.1/thx_Darwin_arm64.tar.gz"
    sha256 "8d5c7f86aab58e71cdcf8ff2c9042bef2a54fc0d9d75da276a856c61cb58c865"

    def install
      bin.install "thx"
    end
  end
end
