# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trove < Formula
  desc "CLI for managing Obsidian vault ideas, projects, and knowledge"
  homepage "https://github.com/peeomid/homebrew-tap"
  version "0.4.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/peeomid/homebrew-tap/releases/download/trove-v0.4.1/trove_Darwin_x86_64.tar.gz"
    sha256 "1682ae92c9ab49cabdb5de8495534617fcb0da9558dea862985de59871bb5433"

    def install
      bin.install "trove"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/peeomid/homebrew-tap/releases/download/trove-v0.4.1/trove_Darwin_arm64.tar.gz"
    sha256 "ce2c8e040c5fb128a1ac736f4884343db67c518041b42f22ac75048e6ed161ad"

    def install
      bin.install "trove"
    end
  end
end
