# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trove < Formula
  desc "CLI for managing Obsidian vault ideas, projects, and knowledge"
  homepage "https://github.com/osimify/trove"
  version "0.4.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/osimify/trove/releases/download/v0.4.0/trove_Darwin_x86_64.tar.gz"
    sha256 "e31a78eff85188d49cc2a277e9e67f7bd38a3768ca8260ed28813480a3295c7a"

    def install
      bin.install "trove"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/osimify/trove/releases/download/v0.4.0/trove_Darwin_arm64.tar.gz"
    sha256 "508a05908b12b2373e0604caf3ec003b977420aed0ab96537f32cb4f3bfd3b26"

    def install
      bin.install "trove"
    end
  end
end
